"""remove unique constraint celular usuario

Revision ID: 1dc1a0e716ac
Revises: f3a1c8e2d947
Create Date: 2026-04-25 23:15:41.839864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc1a0e716ac'
down_revision: Union[str, Sequence[str], None] = 'f3a1c8e2d947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('usuarios_celular_key'), 'usuarios', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('usuarios_celular_key'), 'usuarios', ['celular'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
