"""criando coluna de celular para a entidade usuario

Revision ID: 7e11e2798ca9
Revises: 8785b835354d
Create Date: 2026-04-03 23:58:38.280197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e11e2798ca9'
down_revision: Union[str, Sequence[str], None] = '8785b835354d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('celular', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'usuarios', ['celular'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'celular')
    # ### end Alembic commands ###
