"""criando tabelas iniciais

Revision ID: 8785b835354d
Revises:
Create Date: 2026-04-03 22:28:41.964001

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8785b835354d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("senha_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "perfil",
            sa.Enum("ORGANIZADOR", "PARTICIPANTE", name="perfilusuario"),
            nullable=False,
        ),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "eventos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organizador_id", sa.Uuid(), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=True),
        sa.Column("data_inicio", sa.DateTime(), nullable=False),
        sa.Column("data_fim", sa.DateTime(), nullable=False),
        sa.Column("local", sa.String(length=500), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RASCUNHO", "PUBLICADO", "ENCERRADO", "CANCELADO", name="statusevento"
            ),
            nullable=False,
        ),
        sa.Column(
            "criado_em", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["organizador_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cupons",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("evento_id", sa.Uuid(), nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column(
            "tipo_desconto",
            sa.Enum("PERCENTUAL", "VALOR_FIXO", name="tipodesconto"),
            nullable=False,
        ),
        sa.Column("valor_desconto", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("quantidade_maxima", sa.Integer(), nullable=True),
        sa.Column("quantidade_usada", sa.Integer(), nullable=False),
        sa.Column("valido_ate", sa.DateTime(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["evento_id"],
            ["eventos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fotos_evento",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("evento_id", sa.Uuid(), nullable=False),
        sa.Column("url_thumbnail", sa.String(length=1000), nullable=False),
        sa.Column("url_original", sa.String(length=1000), nullable=False),
        sa.Column("preco", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "publicado_em",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evento_id"],
            ["eventos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lotes_ingresso",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("evento_id", sa.Uuid(), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum("INTEIRA", "MEIA", "PROMOCIONAL", name="tipolote"),
            nullable=False,
        ),
        sa.Column("preco", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("quantidade_total", sa.Integer(), nullable=False),
        sa.Column("quantidade_vendida", sa.Integer(), nullable=False),
        sa.Column("data_inicio_venda", sa.DateTime(), nullable=False),
        sa.Column("data_fim_venda", sa.DateTime(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["evento_id"],
            ["eventos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "relatorios",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("evento_id", sa.Uuid(), nullable=False),
        sa.Column("organizador_id", sa.Uuid(), nullable=False),
        sa.Column("pdf_url", sa.String(length=1000), nullable=True),
        sa.Column(
            "gerado_em", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["evento_id"],
            ["eventos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organizador_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pedidos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("participante_id", sa.Uuid(), nullable=False),
        sa.Column("evento_id", sa.Uuid(), nullable=False),
        sa.Column("cupom_id", sa.Uuid(), nullable=True),
        sa.Column("valor_total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("valor_desconto", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDENTE", "PAGO", "CANCELADO", "REEMBOLSADO", name="statuspedido"
            ),
            nullable=False,
        ),
        sa.Column(
            "criado_em", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["cupom_id"],
            ["cupons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evento_id"],
            ["eventos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["participante_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "compras_foto",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("foto_id", sa.Uuid(), nullable=False),
        sa.Column("pedido_id", sa.Uuid(), nullable=False),
        sa.Column("participante_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["foto_id"],
            ["fotos_evento.id"],
        ),
        sa.ForeignKeyConstraint(
            ["participante_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedidos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pagamentos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pedido_id", sa.Uuid(), nullable=False),
        sa.Column("gateway_transacao_id", sa.String(length=255), nullable=True),
        sa.Column(
            "metodo",
            sa.Enum("PIX", "CARTAO_CREDITO", "BOLETO", name="metodopagamento"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "AGUARDANDO",
                "APROVADO",
                "RECUSADO",
                "ESTORNADO",
                name="statuspagamento",
            ),
            nullable=False,
        ),
        sa.Column("valor", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("pago_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedidos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pedido_itens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pedido_id", sa.Uuid(), nullable=False),
        sa.Column("lote_id", sa.Uuid(), nullable=False),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column("preco_unitario", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["lote_id"],
            ["lotes_ingresso.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedidos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ingressos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pedido_item_id", sa.Uuid(), nullable=False),
        sa.Column("lote_id", sa.Uuid(), nullable=False),
        sa.Column("participante_id", sa.Uuid(), nullable=False),
        sa.Column("qr_code_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ATIVO", "UTILIZADO", "CANCELADO", name="statusingresso"),
            nullable=False,
        ),
        sa.Column("pdf_url", sa.String(length=1000), nullable=True),
        sa.Column(
            "emitido_em", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lote_id"],
            ["lotes_ingresso.id"],
        ),
        sa.ForeignKeyConstraint(
            ["participante_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pedido_item_id"],
            ["pedido_itens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("qr_code_hash"),
    )
    op.create_table(
        "reembolsos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pagamento_id", sa.Uuid(), nullable=False),
        sa.Column("motivo", sa.Text(), nullable=True),
        sa.Column(
            "valor_reembolsado", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("processado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pagamento_id"],
            ["pagamentos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "certificados",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ingresso_id", sa.Uuid(), nullable=False),
        sa.Column("participante_id", sa.Uuid(), nullable=False),
        sa.Column("pdf_url", sa.String(length=1000), nullable=True),
        sa.Column(
            "gerado_em", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["ingresso_id"],
            ["ingressos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["participante_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "checkins",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ingresso_id", sa.Uuid(), nullable=False),
        sa.Column("realizado_por", sa.Uuid(), nullable=False),
        sa.Column(
            "realizado_em",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingresso_id"],
            ["ingressos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["realizado_por"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cortesias",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("evento_id", sa.Uuid(), nullable=False),
        sa.Column("lote_id", sa.Uuid(), nullable=False),
        sa.Column("beneficiado_id", sa.Uuid(), nullable=False),
        sa.Column("emitida_por", sa.Uuid(), nullable=False),
        sa.Column("ingresso_id", sa.Uuid(), nullable=True),
        sa.Column(
            "emitida_em", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["beneficiado_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["emitida_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evento_id"],
            ["eventos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ingresso_id"],
            ["ingressos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lote_id"],
            ["lotes_ingresso.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cortesias")
    op.drop_table("checkins")
    op.drop_table("certificados")
    op.drop_table("reembolsos")
    op.drop_table("ingressos")
    op.drop_table("pedido_itens")
    op.drop_table("pagamentos")
    op.drop_table("compras_foto")
    op.drop_table("pedidos")
    op.drop_table("relatorios")
    op.drop_table("lotes_ingresso")
    op.drop_table("fotos_evento")
    op.drop_table("cupons")
    op.drop_table("eventos")
    op.drop_table("usuarios")
    # ### end Alembic commands ###
