"""adiciona status CANCELADO ao enum StatusPagamento

Revision ID: 926ffd590c99
Revises: 1dc1a0e716ac
Create Date: 2026-04-26 00:13:06.288386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '926ffd590c99'
down_revision: Union[str, Sequence[str], None] = '1dc1a0e716ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
