"""adiciona asaas_customer_id em usuariosajustando coluna de cpf_cnpj com máximo de 14 digitos

Revision ID: ac96aae550b4
Revises: 737c791faa66
Create Date: 2026-04-18 23:50:21.627579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac96aae550b4'
down_revision: Union[str, Sequence[str], None] = '737c791faa66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('asaas_customer_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'asaas_customer_id')
    # ### end Alembic commands ###
