"""adicionando coluna de cpf_cnpj para a tabela usuario

Revision ID: b8ac950013f9
Revises: 7e11e2798ca9
Create Date: 2026-04-18 22:40:30.106923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ac950013f9'
down_revision: Union[str, Sequence[str], None] = '7e11e2798ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('cpf_cnpj', sa.String(length=11), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'cpf_cnpj')
    # ### end Alembic commands ###
